---
abstract: 'Interface to Oyster Account.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Crypt::SSLeay: 0.57
  HTML::TokeParser: 0
  Readonly: 0
  Test::More: 0
  WWW::Mechanize: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Oyster
provides:
  WWW::Oyster:
    file: lib/WWW/Oyster.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
